/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package start-0.1.0.0 */
#ifndef VERSION_start
#define VERSION_start "0.1.0.0"
#endif /* VERSION_start */
#ifndef MIN_VERSION_start
#define MIN_VERSION_start(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_start */

/* package base-4.14.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package ghc-typelits-extra-0.3.3 */
#ifndef VERSION_ghc_typelits_extra
#define VERSION_ghc_typelits_extra "0.3.3"
#endif /* VERSION_ghc_typelits_extra */
#ifndef MIN_VERSION_ghc_typelits_extra
#define MIN_VERSION_ghc_typelits_extra(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_ghc_typelits_extra */

/* package integer-gmp-1.0.3.0 */
#ifndef VERSION_integer_gmp
#define VERSION_integer_gmp "1.0.3.0"
#endif /* VERSION_integer_gmp */
#ifndef MIN_VERSION_integer_gmp
#define MIN_VERSION_integer_gmp(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_integer_gmp */

/* package integer-logarithms-1.0.3 */
#ifndef VERSION_integer_logarithms
#define VERSION_integer_logarithms "1.0.3"
#endif /* VERSION_integer_logarithms */
#ifndef MIN_VERSION_integer_logarithms
#define MIN_VERSION_integer_logarithms(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_integer_logarithms */

/* package number-length-0.2.1.0 */
#ifndef VERSION_number_length
#define VERSION_number_length "0.2.1.0"
#endif /* VERSION_number_length */
#ifndef MIN_VERSION_number_length
#define MIN_VERSION_number_length(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_number_length */

/* package parallel-3.2.2.0 */
#ifndef VERSION_parallel
#define VERSION_parallel "3.2.2.0"
#endif /* VERSION_parallel */
#ifndef MIN_VERSION_parallel
#define MIN_VERSION_parallel(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_parallel */

/* tool doctest-0.17 */
#ifndef TOOL_VERSION_doctest
#define TOOL_VERSION_doctest "0.17"
#endif /* TOOL_VERSION_doctest */
#ifndef MIN_TOOL_VERSION_doctest
#define MIN_TOOL_VERSION_doctest(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  17 || \
  (major1) == 0 && (major2) == 17 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_doctest */

/* tool gcc-11.0.3 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.0.3"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  0 || \
  (major1) == 11 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.1 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.1"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.1 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.1"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.19.12 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.12"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 12)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.10.1 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.1"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "start-0.1.0.0-AMOuWXxhwUMIHDA3usiVc6"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "start-0.1.0.0-AMOuWXxhwUMIHDA3usiVc6"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
