name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest #macos-latest
    strategy:
      matrix:
        stack: ["2.5.1"]
        ghc: ["8.10.2"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1 #.1.4
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        #cabal-version: 'latest' Omitted. 
    
#    - uses: mrkkrp/ormolu-action@v1
#      name: Ormolu formatting 

   # - uses: domdere/haskell-lint-action@master
   #   name: hlinter
        
    - uses: actions/cache@v2
      name: Cache multiple paths
      with:
        path: | 
          ~/.stack
          ~/src
          ~/app
          ~/test
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack
    
    - name: Build
      run: |
        stack build --no-run-tests --no-run-benchmarks
      #stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - run: | 
        runhaskell app/main.hs